- .travis.yml
- Cargo.toml
- seshat-node/lib/index.js
- seshat-node/native/Cargo.toml
- seshat-node/native/src/lib.rs
- seshat-node/test/test.js
- src/config.rs
- src/database.rs
- src/encrypted_dir.rs
- src/encrypted_stream.rs
- src/error.rs
- src/index.rs
- src/lib.rs
- tests/integration_test.rs
This PR implements encrypted storage for Seshat and tries to adress #1. 
We use SQLCipher to encrypt our database, SQLCipher is a SQLite extension which adds transparent AES encryption of the SQLite database.
The Seshat index is as well encrypted using a homegrown encrypted Directory implementation.
The Travis configuration is changed to use Ubuntu Bionic for the Linux build environment since there seems to be an issue with one of our system dependencies (probably SQLCipher) on the default Xenial build environment.
The PR depends on #14, which should be merged before this one.
> Encrypted seshat

- seshat-node/lib/index.js
- seshat-node/native/Cargo.toml
- seshat-node/native/src/lib.rs
- seshat-node/test/test.js
- src/database.rs
- src/events.rs
- tests/integration_test.rs
This patch-set adds the ability to fetch events containing URLs, or events that contain files, from the database easily.
The feature will be useful for clients to quickly show uploaded files files inside of encrypted rooms (e.g. the file panel in riot).
Since those events are of the `m.room.message` type but contain differing `msgtype` values inside of their content the database schema is changed to store the `msgtype` with the event.
The feature may be enhanced at a later state to support exporting all the events, not just file based events, from the database.
> Add the ablility to easily retrieve events containing MXC URLs

- src/database.rs
We store the whole event serialized, and let the caller decide how it
should be serialized. While this puts some responsibilty on the caller,
it allows great flexibility in the case of extensible or custom events.
Storing the value of the content separately ends up storing almost the
whole event twice in the database, the serialized one and the differing
event key/values that are store independently.
The value of the content isn't used anywhere internally so we can safely
remove it from the database. While we do load Event objects from the
database, they are only used internally so it is safe to initialize them
with an empty content value.
> seshat: Don't store the content_value in the database.

- .travis.yml
- seshat-node/lib/index.js
- seshat-node/native/src/lib.rs
- seshat-node/test/test.js
- src/database.rs
- src/index.rs
- tests/integration_test.rs
Tantivy doesn't behave nicely if commit() is called too often on the index writer. A commit means that Tantivy will spawn threads that will try to merge index segments together, that is, it tries to merge a bunch smaller files into one larger.
If users call commit faster than those threads manage to merge the segments, the number of spawned threads keeps on increasing.
This patch limits the number of commit calls we forward to the index writer. To avoid data loss we mark the uncommitted events as such in the database and restore them if needed after a new database object is created.
The PR includes an example binary that can be used to check the behavior of Seshat using differing event counts and  commit rates.
The validity of the patch has been checked using Heaptrack and this example. …
> Tantivy flow control

- seshat-node/lib/index.js
- seshat-node/native/src/lib.rs
- seshat-node/test/test.js
- src/config.rs
- src/database.rs
- src/lib.rs
- tests/integration_test.rs
This pull request implements some improvements to our file loading methods.
It adds the profile to the loaded event and adds the ability to continue loading events in both directions, going backwards in history was the only possibility until now.
The API has been also a bit simplified by using an object with a builder pattern for the arguments.
This is needed to implement https://github.com/matrix-org/matrix-react-sdk/pull/3858 and fix https://github.com/vector-im/riot-web/issues/4959 at least for Riot-desktop.
> Load file events improvements

- src/database.rs
- src/index.rs
These issues were uncovered during live testing with Riot.
Namely: 
* The wrong row id was returned when uncommitted events were added to the database.
* The number of uncommitted events could be larger than `SQLITE_MAX_VARIABLE_NUMBER` if a library user doesn't commit for a while.
* The `Index` didn't count the number of queued up events.
> Couple of issues with the uncommitted events handling.

- seshat-node/lib/index.js
- seshat-node/native/src/lib.rs
- seshat-node/test/test.js
- src/database.rs
- src/events.rs
- src/lib.rs
This PR implements the ability to get some additional stats out of the db, namely the number of events and rooms that are indexed.
This should allow us to show those stats in the UI as was requested in this comment https://github.com/matrix-org/matrix-react-sdk/pull/3672#issuecomment-560109494.
> seshat: Add a method to get more stats out of the database.

- seshat-node/native/Cargo.toml
The dependencies here were used because Seshat didn't wrap the
connection type in its own type. Now that it does they aren't needed
anymore.
> seshat-node: Remove some lingering unused dependencies.

- .travis.yml
- Cargo.toml
- src/config.rs
- src/database/mod.rs
- src/index/mod.rs
- tests/integration_test.rs
This PR makes the encryption feature of Seshat (the Rust crate) an optional feature.
While I don't expect many people to want to disable this feature it might help us with getting our CI running on Windows since there doesn't seem to be an easily installable SqlCipher package there.
The feature is in the set of default features so no changes needed to Seshat-node.
> Optional sqlcipher

- src/index/mod.rs
Tantivy's `IndexReader::reload()` method creates data that only gets garbage collected once a `Searcher` is requested.
A reload is triggered in the default configuration, which we use, on every commit. This means unless users search the index memory usage will rise every time a commit is triggered.
Commits are rather computationally expensive so we should avoid triggering them unless necessary even if we didn't have this problem at hand.
While this doesn't fully remove the rising memory usage it does slow it down considerably since we're reloading only if data has changed.
The complete fix will hopefully land upstream in Tantivy. An issue has been opened upstream https://github.com/tantivy-search/tantivy/issues/777. The fix shouldn't really be controversial or hard.
The first patch …
> Leaky reload mitigations

- Cargo.toml
- src/error.rs
- src/index/encrypted_dir.rs
- src/index/japanese_tokenizer.rs
- src/index/mod.rs
- tests/integration_test.rs
This PR updates to Tantivy 0.12.0. This is needed because 0.12.0 includes the fix for the leaky behavior we got. It includes some breaking changes so a couple API adaptions were needed.
> Updates for Tantivy 0.12.0.

- Cargo.toml
- src/database/connection.rs
- src/database/searcher.rs
- src/events.rs
- src/lib.rs
In order to allow clients to derive things without duplicating full structs on their side, it's useful to have some things derive `Serialize` and `Deserialize`.
Also fixed a doc typo, hope that's ok, let me know if I should make a dedicated PR for that.
> Serde derive

- seshat-node/native/Cargo.toml
- src/database/mod.rs
- src/database/recovery.rs
In the default journaling mode SQLite can end up throwing SQLITE_BUSY
errors in the case of parallel access.
We have a setup with a single writer thread and possibly multiple reader
threads. This is the perfect setup for WAL mode and as per docs[1] will
remove the chance of getting SQLITE_BUSY errors.
[1] https://www.sqlite.org/wal.html
> seshat: Enable WAL mode for the database.

- seshat-node/native/Cargo.toml
- seshat-node/native/src/utils.rs
- seshat-node/test/test.js
- src/database/static_methods.rs
- src/database/writer.rs
This PR adds a couple of fixes to the reporting if events that are added using the `addHistoricEvents()` method were already added.
The database would report that events are added if an empty list was given, while it's true that an empty list is always in the db, we don't want our crawlers to abort further crawling using this checkpoint so report `false` in that special case.
We're also changing a bit the way how we check if an event is in the database, switching to `SELECT COUNT(*)` instead of selecting the row id of the event. This way we can more easily differentiate if an error was raised because no row id was found vs if a database error was thrown.
> Fixes to the reporting if events were already added to the db.

- Cargo.toml
- src/error.rs
[`thiserror`](https://github.com/dtolnay/thiserror) exposes std errors to consumers of seshat, which makes error handling much easier compared to the custom trait exposed by `failure`.
`thiserror` seems to get more traction for various reasons, e.g. some discussion why cranelift switched from `failure` to `thiserror` can be found [here](https://github.com/bytecodealliance/cranelift/pull/1188#issuecomment-547956508).
> Switch from failure to thiserror

- src/config.rs
- src/database/connection.rs
- src/events.rs
As seshat consumer that deals with JSON the additional serde deriving helps with preventing duplicated code and makes working with strongly typed data structures easier.
Might also make sense to check where its now possible to use the derived things in seshat-node.
> seshat: More serde deriving

- src/config.rs
Due to the missing direction default and camelCase renaming `LoadConfig` can't be used as-in for JSON de/serializing.
> seshat: Correctly derive LoadConfig

- seshat-node/native/Cargo.toml
- seshat-node/native/src/lib.rs
- seshat-node/native/src/tasks.rs
- seshat-node/native/src/utils.rs
- src/database/mod.rs
- src/database/recovery.rs
- src/database/searcher.rs
- src/lib.rs
- tests/integration_test.rs
The addition of the `next_batch` token to the return value of the tuple return value of the search was a breaking change.
To avoid further breaking changes if our search return value gains additional fields return a type instead.
> seshat: Use a type as the return value of the search.

- seshat-node/native/Cargo.toml
- src/database/static_methods.rs
This patch mostly just adds a index to make loading the event context fast.
The mean time to load an event context before for my main DB was around 360.96ms, since Riot searches for 10 events at once we repeat that load 10 times and thus resulting in a total load time for the context of 3.62s.
This has now bean reduced to 20.89ms per context and a new total of 0.21s.
We still do two selects per event context which are timed here using the CLI tool separately, first the events that happened before our search result, then events that happened after.
Run Time: real 0.000 user 0.000101 sys 0.000016
Run Time: real 0.017 user 0.012570 sys 0.003698
It is unclear why finding the event after takes this much longer, this was in the 150ms ranges if the newly added index was only over the room_id and …
> database: Improve the load times for the event context.

- src/index/encrypted_stream.rs
This patch changes the way our nonces/IVs are created, while it is quite unlikely that we would encounter an overflow of our counter, considering the files Tantivy creates, this makes sure that it can't happen.
The upper 64 bits are populated by randomness while the lower parts are left 0 initialized.
This aligns the set up to how the counter is created in the attachment encryption part of the Matrix spec as well.
> index: Don't fill out the whole 128 bit counter with randomness.

- seshat-node/lib/index.js
- seshat-node/native/Cargo.lock
- seshat-node/native/Cargo.toml
- seshat-node/native/build.rs
- seshat-node/native/src/lib.rs
- seshat-node/native/src/tasks.rs
- seshat-node/native/src/utils.rs
- seshat-node/package.json
- seshat-node/test/test.js
- seshat-node/yarn.lock
- src/database/recovery.rs
This is a continuation of https://github.com/matrix-org/seshat/pull/95.
It mainly switches to spawning a thread per task instead of using a single thread that waits for tasks on an mpsc channel. The single-thread way of doing things produced some dangling objects and jest would complain about them.
The JS wrapper has also been cleaned up a bit and the exported methods from the Rust side use camel case now.
One thing to mention is, the situation with neon-serde seems to be sad, upstream is unresponsive and it seems that we'll have to start packaging it ourselves.
> Neon update continued

- seshat-node/native/Cargo.lock
- seshat-node/native/Cargo.toml
- seshat-node/native/src/utils.rs
This PR switches out to our own release of neon-serde since upstream seems to be unresponsive and practically dead.
This is needed because we bumped our neon version due to the latest Electron requiring a fresher neon release and neon-serde needs to track the neon version.
> seshat-node: Switch to our released fork of neon-serde

- src/database/mod.rs
- src/database/recovery.rs
- src/database/static_methods.rs
- src/database/writer.rs
- src/index/encrypted_dir.rs
- src/index/encrypted_stream.rs
- src/index/mod.rs
- tests/integration_test.rs
Passing a search term "in quotes" while also passing a room_id fails with a `IndexError(InvalidArgument("Query is invalid. SyntaxError"))`
This is because to pass a room_id, we suffix the query with the room ID clause, then append `AND "<search term>"` (i.e. the search term is explicitly quoted).
This means -
* Quoting it again breaks, and Tantivy natural search operators (e.g. AND, OR, brackets) I think are being ignored
* We're always running quoted search when a room ID is passed, which is unexpected - I think users would expect an ANDed search
So I've removed the quotes.. if that causes some other issue, maybe there's another way.
> Fix quote search when passing a room_id

- src/index/mod.rs
- tests/integration_test.rs
Without the brackets, multiple words in the query causes a syntax error.
I guess Tantivy gets confused if you provide the AND operator in some places but not others.
> Bracket search terms

- .pre-commit-config.yaml
- README.md
Run clippy and `cargo fmt` in precommit, similarly to CI.
> Add precommit hooks
